### ISSUE TITLE
no values in classes/functions/constants

### ISSUE THREAD

**Issue by marcel-liebgott** [script-solution/PHPCheck#3]
After Update (ac53043) the PHPRef-scanner don't persist any "phpman" run.
Observation:
PHPRef-scanner detect 13054 files
each file run without any (db-)error
no classes/functions/constants found

**Comment by hrniels** [comment]
It works for me as I've just tested with a fresh installation.

Have you started a new database with the current structure.sql? (it has changed)
Have you changed PC_PHP_EXEC in config/userdef.php?

**Comment by marcel-liebgott** [comment]
some crashed by pull the current version - sorry
